function filter(m,el){var bar=document.getElementById('filterbar');bar.querySelectorAll('.chip').forEach(function(c){c.classList.remove('on')});el.classList.add('on');var g=document.getElementById('grid');g.classList.add('fading');
    setTimeout(function(){document.querySelectorAll('#grid .card').forEach(function(c){var mine=c.getAttribute('data-mine')==='1';c.style.display=(m===0||(m===1&&mine)||(m===2&&!mine))?'':'none';});g.classList.remove('fading');showline();},160);}
  function afilter(k,el){[...el.parentElement.children].forEach(c=>c.classList.remove('on'));el.classList.add('on');
    document.querySelectorAll('#alerts .alert').forEach(a=>{a.style.display=(k==='all'||a.getAttribute('data-k')===k)?'':'none';});}
  async function needLogin(r){if(r.status===401){alert('Sessao expirada. Faca login de novo.');location.href='/login';return true;}return false;}
  async function addGame(el){const appId=document.getElementById('appid').value.trim();const label=document.getElementById('lbl').value.trim();
    if(!appId)return alert('Digite o AppID (so numeros, ex 557040)');if(el){el.textContent='Adicionando...';el.disabled=true;}const r=await fetch('/api/games',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appId,mine:true,label})});if(await needLogin(r))return;if(!r.ok){const e=await r.json().catch(()=>({}));alert('Falha: '+(e.error||r.status));if(el){el.textContent='+ Adicionar';el.disabled=false;}return;}location.reload();}
  async function seedDemo(el){if(el){el.textContent='Carregando...';el.disabled=true;}const r=await fetch('/api/games/seed',{method:'POST'});if(await needLogin(r))return;if(!r.ok){alert('Falha ao carregar demo');if(el){el.textContent='CARREGAR 3 JOGOS DEMO';el.disabled=false;}return;}location.reload();}
  async function removeGame(appId,el){if(!confirm('Remover App '+appId+' do monitoramento?'))return;if(el){el.textContent='...';el.disabled=true;}const r=await fetch('/api/games/'+appId,{method:'DELETE'});if(await needLogin(r))return;if(!r.ok){alert('Falha ao remover');if(el){el.textContent='Remover';el.disabled=false;}return;}location.reload();}
  async function recheck(appId,el){const b=el||event.target;b.textContent='Coletando...';b.disabled=true;try{const r=await fetch('/api/check/'+appId);if(await needLogin(r))return;if(!r.ok){const e=await r.json().catch(()=>({}));b.textContent='Recheck';b.disabled=false;alert('Falha: '+(e.error||r.status));return;}}catch(e){b.textContent='Recheck';b.disabled=false;alert('Falha de rede. Tente de novo.');return;}location.reload();}
  async function runWorker(el){const b=el||event.target;b.textContent='Coletando...';b.disabled=true;try{const r=await fetch('/api/worker',{method:'POST'});if(await needLogin(r))return;const j=await r.json().catch(()=>null);alert(j&&j.result?j.result.join('\n'):'Coleta concluida');}catch(e){alert('Falha de rede. Tente de novo.');}location.reload();}
  function csv(){window.location='/api/export.csv';}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login';}
  async function plan(){const r=await fetch('/api/billing').then(x=>x.json());const el=document.getElementById('planline');if(el)el.textContent='Plano '+r.plan.toUpperCase()+' · '+(r.plan==='pro'?'ativo':('trial: '+r.trialLeft+' dias restantes'))+' · R$ 99/mes';alert(JSON.stringify(r));}
  async function checkout(){const r=await fetch('/api/billing/checkout',{method:'POST'}).then(x=>x.json());alert((r.next||'ok')+' Chave Pix: '+(r.pixKey||''));}
  async function saveKey(){const v=document.getElementById('swkey').value.trim();await fetch('/api/steamworks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:v})});alert('Key salva. Use Testar wishlist real.');}
  async function checkWish(){const g=await fetch('/api/games').then(x=>x.json());const appId=(g[0]&&g[0].appId)||'557040';const r=await fetch('/api/wishlist/'+appId).then(x=>x.json());alert(r.configured===false?'Sem key: usando reviews como proxy.':JSON.stringify(r).slice(0,300));}
  async function showAudit(appId,el){const box=document.getElementById('x-'+appId);box.textContent='Analisando pagina...';if(el)el.disabled=true;try{const r=await fetch('/api/audit/'+appId).then(x=>x.json());
    if(r.error){box.textContent=r.error;return;}
    box.innerHTML='<b>Auditoria '+r.score+'/100</b> · desc '+r.shortLen+' chars · '+r.shots+' shots · '+r.trailers+' trailer(s)<br/>'+(r.issues.length?r.issues.map(i=>'− '+i).join('<br/>'):'Sem problemas criticos.');}catch(e){box.textContent='Falha de rede. Tente de novo.';}finally{if(el)el.disabled=false;}}
  async function showForecast(appId,el){const box=document.getElementById('x-'+appId);box.textContent='Calculando...';if(el)el.disabled=true;try{const r=await fetch('/api/forecast/'+appId).then(x=>x.json());
    if(r.error){box.textContent=r.error;return;}
    box.innerHTML='<b>'+r.band+'</b>'+(r.next?'<br/>Faltam cerca de <b>'+r.need+'</b> avaliacoes positivas seguidas para chegar a <b>'+r.next+'</b>.':'<br/>Sem projecao (base pequena ou topo da escala).');}catch(e){box.textContent='Falha de rede. Tente de novo.';}finally{if(el)el.disabled=false;}}
  async function showReply(appId,el){const box=document.getElementById('x-'+appId);box.textContent='Buscando reviews...';if(el)el.disabled=true;try{const r=await fetch('/api/reply/'+appId).then(x=>x.json());
    if(!r.draft){box.textContent='Sem reviews recentes para rascunhar.';return;}
    box.innerHTML='<b>Rascunho PT:</b> '+r.draft.pt+'<br/><br/><b>Draft EN:</b> '+r.draft.en+'<br/><button class="btn ghost small" style="margin-top:6px" onclick="navigator.clipboard.writeText(this.parentElement.innerText);this.textContent=\'Copiado\'">Copiar</button>';}catch(e){box.textContent='Falha de rede. Tente de novo.';}finally{if(el)el.disabled=false;}}
  async function saveWh(){const v=document.getElementById('wh').value.trim();await fetch('/api/config/webhook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:v})});alert('Webhook salvo. Use Testar alerta.');}
  async function testWh(){const r=await fetch('/api/discord/test',{method:'POST'}).then(x=>x.json());
    if(r.ok&&!r.simulated){alert('Alerta de teste enviado ao Discord.');}
    else if(r.ok){alert('Sem webhook salvo: registrado apenas no log do servidor.');}
    else{alert('Falha: '+(r.error||'verifique o webhook'));}}
  async function bulk(){const t=document.getElementById('bulk').value;if(!t)return alert('Cole ao menos um AppID ou URL');const r=await fetch('/api/games/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:t})}).then(x=>x.json());alert(r.added+' jogo(s) adicionado(s).');location.reload();}
  function cd(id,iso){const el=document.getElementById(id);if(!el)return;const d=Math.ceil((new Date(iso)-Date.now())/86400000);el.textContent=d>0?('faltam '+d+' dias'):(d===0?'comeca hoje':'em andamento ou encerrado');}
  cd('cd1','2026-10-19T10:00:00-03:00');cd('cd2','2027-02-13T10:00:00-03:00');